version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  servicio1:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: contenedor1
    ports:
      - "8501:8501"
    volumes:
      - ./back-end:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379