services:
  frontend:
    build:
      context: ./Front-End
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  backend:
    build:
      context: ./Back-End
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
